### ISSUE TITLE
Python Unicode string stored as \u0410\u0433\u0430.

### ISSUE THREAD

**Issue by zsofts** [R3gm/SoniTranslate#10]
Hi, Thank you for your work!, there is a small problems with displaying encoding.
Small snippet of example: 
Generated subtitles:
{
    "start": 19.768,
    "text": "\u0410\u0433\u0430."
  },

Here is a description of this problem and a solution: https://stackoverflow.com/questions/11094380/python-unicode-string-stored-as-u84b8-u6c7d-u5730-in-file-how-to-convert-it

**Comment by R3gm** [comment]
Thanks for the help!
