### ISSUE TITLE
huggingface_hub.errors.LocalEntryNotFoundError:

### ISSUE THREAD

**Issue by Harooon1892** [R3gm/SoniTranslate#103]
Hello,

I receive the following error when I upload a video locally and start SoniTranslate:

huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

Can someone help me with this?

**Comment by alexnikospb** [comment]
> Hello,
> 
> I receive the following error when I upload a video locally and start SoniTranslate:
> 
> huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
> 
> Can someone help me with this?

Hello, how did you solve this error?

**Comment by timki0n** [comment]
Hi, so how did you solve this problem?
