### ISSUE TITLE
Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}

### ISSUE THREAD

**Issue by SAER2023** [R3gm/SoniTranslate#107]
i install CUDA Toolkit 11.8  and cuDNN 9.5.0  and all requirements files

but error show

```
Suppressing numeral and symbol tokens
Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}
Invalid handle. Cannot load symbol cudnnCreateConvolutionDescriptor
```
any help

**Comment by levi-creator-max** [comment]
Why  not?

**Comment by Th3Operator** [comment]
> i install CUDA Toolkit 11.8 and cuDNN 9.5.0 and all requirements files
> 
> but error show
> 
> ```
> Suppressing numeral and symbol tokens
> Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}
> Invalid handle. Cannot load symbol cudnnCreateConvolutionDescriptor
> ```
> 
> any help

i got the same error in google colab, although i didn't install anything

**Comment by levi-creator-max** [comment]
Then who installed that? I didn't do that kind of thing! I was just waiting patiently!

**Comment by levi-creator-max** [comment]
Alright, everybody, let's have a meeting!

**Comment by ahm202024** [comment]
i try it on google colab without installing CUDA Toolkit 11.8 and cuDNN 9.5.0 show same error, i run colab notebook and i get same error, i try it on lighting ai with different gpu like L4 and L40s same error

**Comment by SAER2023** [comment]
the error show when i click Translate in webui

**Comment by SAER2023** [comment]
ok it fixed thanks
