### ISSUE TITLE
Selecting a speaker in the subtitle editor

### ISSUE THREAD

**Issue by zsofts** [R3gm/SoniTranslate#12]
The definition of speaker does not always work correctly. Instead of a female voice, maybe a male voice and vice versa. Is it possible to make it so that the speaker can be assigned in subtitles edit?
Let's say something like:
```
   {
     "speaker": 1,
     "start": 1.172,
     "text": "Your work is very cool."
   },
   {
     "speaker": 3,
     "start": 2.372,
     "text": "Yes, I agree too, SoniTranslate is great."
   }
```

So that if necessary, you could fix it manually.

**Comment by R3gm** [comment]
Hi @zsofts,
Yes, absolutely! I understand your suggestion, and I'll start working on this improvement soon.
