### ISSUE TITLE
[WinError 2] The system cannot find the specified file (Windows)

### ISSUE THREAD

**Issue by gellote** [R3gm/SoniTranslate#18]
Hi, I just installed and ran sonitranslate and everything works fine.
But the problem is that it only works when I pass it a YouTube url, but when I want to upload a file locally it gives me the error "[WinError 2] The system cannot find the specified file".
I attach the details of the console.
![image](https://github.com/R3gm/SoniTranslate/assets/102249689/767528b5-397d-4f0e-81a8-819d76492a87)

**Comment by gellote** [comment]
If I add the file path in quotes it no longer gives me the error that the file cannot be found but it gives me this error.
![image](https://github.com/R3gm/SoniTranslate/assets/102249689/957c7ce7-424e-49b4-810d-3634509c14c8)

**Comment by R3gm** [comment]
Hi, you've checked that ffmpeg is installed correctly with `ffmpeg - h`?
Which version of Windows are you currently using?

**Comment by gellote** [comment]
Hello, I am using windows 11.
The ffmpeg -h command does not return any errors.

![image](https://github.com/R3gm/SoniTranslate/assets/102249689/59c626af-e299-46a1-b309-d03905fcecc1)

**Comment by tinogithub** [comment]
Hello,
almost the same error here. Using an URL works. 
FFMPEG installed and running Windows 10 Build 19045

![sonitranslate_error](https://github.com/R3gm/SoniTranslate/assets/23121904/914ae61a-94ae-42cf-9f24-671922549086)

**Comment by gellote** [comment]
Hello, what information does the console give you if you choose to upload the file as a path in quotes? for example "C:\Users\pc\Downloads\VideoExample.mp4"

**Comment by gellote** [comment]
Could it have something to do with this?
![image](https://github.com/R3gm/SoniTranslate/assets/102249689/ec725984-158e-4a69-803a-d98577832251)

**Comment by R3gm** [comment]
> Hello, what information does the console give you if you choose to upload the file as a path in quotes? for example "C:\Users\pc\Downloads\VideoExample.mp4"

Without quotes

![mc-Sin título (2)](https://github.com/R3gm/SoniTranslate/assets/114810545/ba878c67-62c6-44b7-b774-1cc4635d866b)

In Windows 10, I used the Anaconda PowerShell prompt.

**Comment by gellote** [comment]
I reinstalled everything but it still gives me the same audio error.
I also use Anaconda PowerShell prompt and get the same error.

**Comment by tinogithub** [comment]
In my case it works now although I haven't changed anything but starting the service again.

**Comment by gellote** [comment]
Maybe it's a problem with Windows 11 in my case

**Comment by gellote** [comment]
I applied the correction you made to the preprocessor.py file and now it works perfectly for both the submit video and the path.
You are a genius, it is a great project.
If you allow me, I would like to suggest some features such as being able to upload more than
 one files in queue so as not to have to add one by one and also another feature would be that the name of the output file by default would have the name of the source file and the word translation at the end so as not to have to keep changing for each file to the time.
Sorry for my English, I'm using Google Translator because I speak Spanish.
It's a great project, I'll keep an eye out for updates. thank you

**Comment by R3gm** [comment]
Thank you for your suggestions
I'll explore implementing them in future updates
Additionally, creating a Windows 11 installation guide would be very helpful for users, if you're able to create one  based on your experience, it would benefit others using the same operating system

**Comment by ToiYeuTien** [comment]
> Tôi đã áp dụng chỉnh sửa mà bạn đã thực hiện cho tệp preprocessor.py và bây giờ nó hoạt động hoàn hảo cho cả video gửi và đường dẫn. Bạn là một thiên tài, đó là một dự án tuyệt vời. Nếu bạn cho phép, tôi muốn đề xuất một số tính năng như có thể tải lên nhiều tệp trong hàng đợi để không phải thêm từng tệp một và một tính năng khác là tên tệp đầu ra mặc định sẽ có tên của file nguồn và phần dịch chữ ở cuối nên bạn không cần phải xem từng file cùng lúc. Xin lỗi vì tiếng Anh của tôi, tôi đang sử dụng Google Translator vì tôi nói tiếng Tây Ban Nha. Đó là một dự án tuyệt vời, tôi sẽ theo dõi các thông tin cập nhật. Cảm ơn



> I applied the correction you made to the preprocessor.py file and now it works perfectly for both the submit video and the path. You are a genius, it is a great project. If you allow me, I would like to suggest some features such as being able to upload more than one file in queue so as not to have to add one by one and also another feature would be that the default output file name would have the name of the source file and the word translation at the end so you don't have to go through each file at the same time. Sorry for my English, I'm using Google Translator because I speak Spanish. It's a great project, I'll keep an eye out for updates. thank you

Hello!
Could you please guide me on how to install the program on Windows 11? I'm having trouble installing Piper-TTS, and when I try to run the program, I receive the following error message:

`(SoniTr)` D:\Stable\Sound_to_Text\SoniTranslate>python app_rvc.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "D:\Stable\Sound_to_Text\SoniTranslate\app_rvc.py", line 68, in <module>
    from voice_main import ClassVoices
  File "D:\Stable\Sound_to_Text\SoniTranslate\voice_main.py", line 14, in <module>
    from fairseq import checkpoint_utils
  File "D:\.Conda\envs\SoniTr\lib\site-packages\fairseq\__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "D:\.Conda\envs\SoniTr\lib\site-packages\fairseq\dataclass\initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "D:\.Conda\envs\SoniTr\lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "D:\.Conda\envs\SoniTr\lib\site-packages\hydra\utils.py", line 10, in <module>
    from hydra._internal.utils import (
  File "D:\.Conda\envs\SoniTr\lib\site-packages\hydra\_internal\utils.py", line 16, in <module>
    from omegaconf._utils import get_ref_type
ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils' `(D:\.Conda\envs\SoniTr\lib\site-packages\omegaconf\_utils.py)`

Looking forward to hearing from you!

**Comment by ToiYeuTien** [comment]
> > > Tôi đã áp dụng chỉnh sửa mà bạn đã thực hiện cho tệp preprocessor.py và bây giờ nó hoạt động hoàn hảo cho cả video gửi và đường dẫn. Bạn là một thiên tài, đó là một dự án tuyệt vời. Nếu bạn cho phép, tôi muốn đề xuất một số tính năng như có thể tải lên nhiều tệp trong hàng đợi để không phải thêm từng tệp một và một tính năng khác là tên tệp đầu ra mặc định sẽ có tên của file nguồn và phần dịch chữ ở cuối nên bạn không cần phải xem từng file cùng lúc. Xin lỗi vì tiếng Anh của tôi, tôi đang sử dụng Google Translator vì tôi nói tiếng Tây Ban Nha. Đó là một dự án tuyệt vời, tôi sẽ theo dõi các thông tin cập nhật. Cảm ơn
> > 
> > 
> > > I applied the correction you made to the preprocessor.py file and now it works perfectly for both the submit video and the path. You are a genius, it is a great project. If you allow me, I would like to suggest some features such as being able to upload more than one file in queue so as not to have to add one by one and also another feature would be that the default output file name would have the name of the source file and the word translation at the end so you don't have to go through each file at the same time. Sorry for my English, I'm using Google Translator because I speak Spanish. It's a great project, I'll keep an eye out for updates. thank you
> > 
> > 
> > Hello! Could you please guide me on how to install the program on Windows 11? I'm having trouble installing Piper-TTS, and when I try to run the program, I receive the following error message:
> > `(SoniTr)` D:\Stable\Sound_to_Text\SoniTranslate>python app_rvc.py The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows. The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows. Traceback (most recent call last): File "D:\Stable\Sound_to_Text\SoniTranslate\app_rvc.py", line 68, in from voice_main import ClassVoices File "D:\Stable\Sound_to_Text\SoniTranslate\voice_main.py", line 14, in from fairseq import checkpoint_utils File "D:.Conda\envs\SoniTr\lib\site-packages\fairseq__init__.py", line 29, in from fairseq.dataclass.initialize import hydra_init File "D:.Conda\envs\SoniTr\lib\site-packages\fairseq\dataclass\initialize.py", line 8, in from hydra.core.config_store import ConfigStore File "D:.Conda\envs\SoniTr\lib\site-packages\hydra__init__.py", line 5, in from hydra import utils File "D:.Conda\envs\SoniTr\lib\site-packages\hydra\utils.py", line 10, in from hydra._internal.utils import ( File "D:.Conda\envs\SoniTr\lib\site-packages\hydra_internal\utils.py", line 16, in from omegaconf._utils import get_ref_type ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils' `(D:\.Conda\envs\SoniTr\lib\site-packages\omegaconf\_utils.py)`
> > Looking forward to hearing from you!
> 
> You can try running these commands in your terminal:
> 
> ```
> conda activate sonitr
> pip install omegaconf==2.0.6
> ```

"Thank you for this wonderful program, I have installed and used it, but the only issue is that the audio between segments overlaps, I have tried increasing and decreasing the speed of 'Max Audio acceleration' but it didn't work, I have also tried slowing down the video before processing it but it didn't help. Do you have any way to avoid overlapping audio?"
