### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Denskl1** [R3gm/SoniTranslate#4]
Hello, I'm deploying on a computer, it seems that everything is installed. I get the link, everything works. I insert a token, and a link to the video, then an error pops up. What's wrong?
Initial log:
![изображение](https://github.com/R3gm/SoniTranslate/assets/143549874/d29e7d26-7c7a-4a1b-9e3e-27e355a35d1c)
end log with error:
![изображение](https://github.com/R3gm/SoniTranslate/assets/143549874/909cc0a4-9e05-4b42-bec0-1e38e36fa40b)
Thanks a lot! Good luck)

**Comment by R3gm** [comment]
Hello @Denskl1 , the program is not designed to run on Windows at the moment, but the error could be related to ffmpeg not being found in the system, so it needs to be installed; ffmpeg is a multimedia framework and you can install it on Windows by following this [tutorial](https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/).

**Comment by R3gm** [comment]
Hi @Denskl1
I've addressed the Colab issue. Could you kindly confirm if it's working for you now? Have a wonderful day!

**Comment by Denskl1** [comment]
Hello! Yes, now everything seems to be working, the only thing is that an error occurs at the end of the process.
![изображение](https://github.com/R3gm/SoniTranslate/assets/143549874/3498b8a4-1389-4695-9a1c-a8dddd98edba)
![изображение](https://github.com/R3gm/SoniTranslate/assets/143549874/cb538496-a404-485e-a449-4cb632c56495)
It seems that there is no way where to save the file, or some kind of permission.
What could it be?
Thanks, have a great day!

**Comment by Denskl1** [comment]
Hello, everything is working. Thanks a lot, have a great day!

**Comment by R3gm** [comment]
Hi @Denskl1,

I'm delighted to hear that everything is working for you now! If you have any more questions please don't hesitate to reach out. Have a fantastic day!

**Comment by Denskl1** [comment]
hello, please help me with the settings. Everything works, thank you. But when translating, when the speech is fast, it seems to start to accelerate, and does not finish the sentence. I suspect that somewhere the settings need to be changed?

**Comment by R3gm** [comment]
Hi @Denskl1,

In line 557 and 558 of the `app_rvc.py` file, the variable `porcentaje` is currently set to 2.1 (Specifically, this setting accelerates the audio playback by 2.1 times when the duration difference is very high ). This value was chosen to address issues of audio overlapping that were occurring in many videos, or when the timestamps are not detected correctly.

Modifying this value might help in slowing down the audio playback. However, please keep in mind that this change could potentially cause issues with audio overlapping.

Default:
```
        if porcentaje > 2.1:
            porcentaje = 2.1
```
You can experiment with different values for `porcentaje` to see if it resolves the problem. Try reducing the value gradually until you find a setting that prevents the audio from accelerating too much during fast speech. 

For instance, you can try:
```
        if porcentaje > 1.5:
            porcentaje = 1.5
```

**Comment by Aydar18** [comment]
Hello! Is the program running now? I decided to try online, but I always get the same error:
Error
Error can't create the audio file: ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers built with gcc 12 (Debian 12.2.0-14) configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared libavutil 57. 28.100 / 57. 28.100 libavcodec 59. 37.100 / 59. 37.100 libavformat 59. 27.100 / 59. 27.100 libavdevice 59. 7.100 / 59. 7.100 libavfilter 8. 44.100 / 8. 44.100 libswscale 6. 7.100 / 6. 7.100 libswresample 4. 7.100 / 4. 7.100 libpostproc 56. 6.100 / 56. 6.100 [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5587309d3dc0] moov atom not found Video.mp4: Invalid data found when processing input
