### ISSUE TITLE
Tutorial video

### ISSUE THREAD

**Issue by DEV-MalletteS** [R3gm/SoniTranslate#49]
Hey, I didn't know how to contact you so I'm posting an issue here instead 😂

I made a tutorial video on how to use it, it's for a presentation

https://youtu.be/SmGkFaSzq_Q?si=16Jt9K144qtdCaR6

Fine with me if you want to use it.

**Comment by R3gm** [comment]
Hi @DEV-MalletteS,

Thanks a bunch for sharing the tutorial video! I really appreciate the effort you put into creating it. It'll definitely be added to the README. Thanks again

**Comment by DEV-MalletteS** [comment]
You're welcome! Looks great in the readme, great addition.
