### ISSUE TITLE
New TTS multilingual model with voice cloning

### ISSUE THREAD

**Issue by 4eJIoBek1** [R3gm/SoniTranslate#5]
I love this webui!
Coqui released XTTS that will be ideal for sonitranslate

https://huggingface.co/spaces/coqui/xtts

**Comment by R3gm** [comment]
Hi @4eJIoBek1  
I'll definitely explore how I can implement it effectively to enhance the sonitranslate experience. Your input is much appreciated!
Thank you

**Comment by zsofts** [comment]
Bark tts good too

**Comment by b4zz4** [comment]
Another simpler option is to imitate the tone of the voice, to distort without changing the duration

https://stackoverflow.com/questions/40564451/how-to-change-pitch-and-tempo-together-reliably-with-ffmpeg

**Comment by b4zz4** [comment]
I made a simple example of how you could look for the audio section and detect the tone of the voice and change the tone created to imitate the original voice:

https://gist.github.com/b4zz4/312bb5c17668f9e600c57fd0857c8640

This function already has the displacement in the second of start and end.

Something positive would be to separate the voice from the ambient sound using spleeter (or something similar) to just use voices without ambient sound.
