### ISSUE TITLE
I would like to suggest a couple of functions

### ISSUE THREAD

**Issue by zsofts** [R3gm/SoniTranslate#7]
Hello, your creation is beautiful!
I would like to suggest a couple of functions.
From simple:
Add a checkbox on/off audio acceleration
In the audio mixer output settings (detailed volume settings((volume percentage))
RVC settings (index_rate, rms_mix_rate, protect)
From a more complex one:
Save .srt subtitles files in the original and target languages.
Editing the translated subtitle (a field in which the translation text will be and it can be changed, save and then once again assembling the sound and applying the RVС)

**Comment by R3gm** [comment]
Hi, 
Great! Thanks for the suggestions! I'll definitely keep them in mind and work on implementing them.

**Comment by R3gm** [comment]
Hi @zsofts,
I have added the options except for those of RVC. I am thinking of changing the system to XTTS. In the future, I will decide whether to switch it to RVC or to keep both and develop them further.
