### ISSUE TITLE
I would like to add lip sync.

### ISSUE THREAD

**Issue by NeuroDonu** [R3gm/SoniTranslate#8]
Hi,
I would like to add lip sync in separate tab by using [SadTalkerVideo-Lip](https://github.com/NeuroDonu/SadLIpFIX) (my fixed fork) or [video-retalking](https://github.com/OpenTalker/video-retalking).
I would also like to translate it into my own language. 

I hope you like the first idea and add it.

**Comment by R3gm** [comment]
Hi @NeuroDonu,
It's an incredible idea. First, we need to see if there's library compatibility because ultimately, I've had problems with that. If there are no issues with it and you implement it, there's no doubt I'll add it to SoniTranslate

**Comment by NeuroDonu** [comment]
There is only one minus, the libraries are a little outdated, but I think a little old pytorch and cuda will not play a big role.

**Comment by R3gm** [comment]
Understood, but let's ensure the stability given the potential compatibility issues
Thanks

**Comment by DEV-MalletteS** [comment]
Wav2Lip would potentially work or facefusion codes that they are using to do so with another face.
