### ISSUE TITLE
Pydantic Schema Generation Error with starlette.requests.Request

### ISSUE THREAD

**Issue by Wellingtonxd** [R3gm/SoniTranslate#86]
When using FastAPI with Pydantic, an error occurs related to schema generation for starlette.requests.Request. This issue surfaces while processing request bodies, and it is due to Pydantic's inability to generate a schema for the Request class.

Error Traceback:
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

Could you provide guidance on how to resolve this issue? If there is a known fix or workaround, or if this issue has been addressed in a newer version, please let us know.
![Captura de Tela (36953)](https://github.com/user-attachments/assets/19dfe4d6-d0a7-4e27-9449-5816c823c2d0)
This error has been occurring for 2 days. The collab and local versions have the same error.

**Comment by eyewee** [comment]
True, same here, need a fix please!

**Comment by levi-creator-max** [comment]
Oh and R3gm, can you add Filipino and any other languages to SoniTranslate that can be used for Translating the audio, video and document? 'Cause I wanna try with Filipino and any other languages! Also, let me know when you can update SoniTranslate at HuggingFace!

**Comment by levi-creator-max** [comment]
R3gm, I'm sorry to rush you, but like I was asking, can you add Filipino, Esperanto and any other new languages to SoniTranslate that can be used for Translating the audio, video and document? 'Cause I wanna try with Filipino, Esperanto, and any other new languages! Also, let me know when you can update SoniTranslate at HuggingFace!

**Comment by Wellingtonxd** [comment]
It seems that R3gm will not respond :(

**Comment by levi-creator-max** [comment]
Okay, then, where is he? I want him to update to add Filipino, Esperanto, and any other languages to SoniTranslate for translating audio and video.

**Comment by levi-creator-max** [comment]
Okay, then, where is he? I want him to update to add Filipino, Esperanto, and any other languages to SoniTranslate for translating audio and video. If he will not respond, then who will update it on HuggingFace and duplicate it without the token? Now where is R3gm?

**Comment by Wellingtonxd** [comment]
The bug has been fixed. Thanks, R3gm!

**Comment by levi-creator-max** [comment]
And I see you already set up Tagalog language
